server:
  port: 8001

jwt:
  secret: "secret-key"

login:
  user: "admin"
  password: "password"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  accessKeyID: "minio"
  secretAccessKey: "minio123"
  useSSL: false
  bucket: "portfolio.backend"

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "portfolio"
  sslmode: "disable"

